### ISSUE TITLE
For Audio Only `.mp4` / `.mov` the generic audio wave gif is not extracted

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#90] opened 2024-01-30 10:23 UTC
I just noticed that with audio only `.mp4` / `.mov` files our generic audio wave `.gif` is not extracted out. Only the .json and icons are extracted out.

This was possible on our earliest build. 

<img width="1588" alt="audio-only" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/6bf1ef43-019a-4860-a71e-6d2884a66878">

SH Script

```bash
$TOOL_PATH "$FCPXML_PATH" "$OUTPUT_DIR" --export-format notion --image-format gif --result-file-path $RESULT_JSON --log-level debug --log $ERROR_LOG
```

Attached animated gif.
[audio-wave.gif.zip](https://github.com/TheAcharya/MarkersExtractor/files/14096253/audio-wave.gif.zip)

**Comment by orchetect** [comment] 2024-02-20 06:08
Do you mean when the generated media file for use with MarkersExtractor has no video track and only has an audio track?

With 0.3.3:

- PNG thumbnails seem to work fine. I ran a test with an audio-only clip. Markers output the placeholder wave image.
- Using GIF thumbnails it's not finding any video frames and fails to create the gif file. This looks to be a bug and should output the placeholder wave animation.

**Comment by orchetect** [comment] 2024-02-20 06:11
I may have found the issue. It's correctly using the placeholder animation but it may be trying to request frames that don't exist (ie: at a time corresponding to the original timeline and not offset to the placeholder video's start).

**Comment by IAmVigneswaran** [comment] 2024-02-20 06:15
> Do you mean when the generated media file for use with MarkersExtractor has no video track and only has an audio track?

Yes. Just Audio in the Primary Storyline. Without any video.

> PNG thumbnails seem to work fine.

PNG thumbnails seem to work.

> This looks to be a bug and should output the placeholder wave animation.

Only the pre-rendered GIFs are not extracted.

**Comment by orchetect** [comment] 2024-02-20 06:38
Further debugging - seems like a thread related issue. The file is actually being written, but the operation never completes so the file remains a hidden temporary file.

**Comment by IAmVigneswaran** [comment] 2024-02-20 07:00
Interesting!

**Comment by orchetect** [comment] 2024-02-20 07:00
Further narrowing down. Seems to be a regression in the way the image converter handles images that don't exist in a source video.

**Comment by IAmVigneswaran** [comment] 2024-02-20 07:10
> (We don't actually store a hard-coded gif file of the audio wave in the executable. It's a small 40KB 1-second long .mov file that the executable is converting to a gif file at the respective input dimensions and settings.)

I believe this was possible in our earlier much builds before your major refactor of codebase.

Much like our marker Icons, we could store and hardcode the GIF within the code?

**Comment by orchetect** [comment] 2024-02-20 07:20
> we could store and hardcode the GIF within the code

There's no point, the above explains why our current implementation is preferable.

**Comment by orchetect** [comment] 2024-02-20 07:24
This should be fixed for next release 0.3.4. Needs some testing to see if typical project conversions still work as expected.

**Comment by IAmVigneswaran** [comment] 2024-02-20 08:36
> This should be fixed for next release 0.3.4. Needs some testing to see if typical project conversions still work as expected.

Just did a quick test with [test-build](https://github.com/TheAcharya/MarkersExtractor/actions/runs/7970422994).

Seems to be working. Thank you!

<img width="306" alt="audio-only-test" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/845e2ad5-0e7f-4c59-b67f-aeb63fde5ebd">

Will test further with other timelines.

**Comment by IAmVigneswaran** [comment] 2024-02-27 02:52
I just tested with a Test Build of [Marker Data](https://github.com/TheAcharya/MarkerData/actions/runs/8058144288)

For some reason, it is not working. 

When building, I assume it is pulling the latest changes from this repo?

**Comment by orchetect** [comment] 2024-02-27 02:58
No, it's taking the latest release.

**Comment by IAmVigneswaran** [comment] 2024-02-27 03:19
Noted!

**Closed** 2024-04-23 10:48 UTC
Labels: bug
