### ISSUE TITLE
Default values of Roles are missing - 0.2.0-alpha-20230101.0

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#33] opened 2023-01-02 03:14 UTC
@orchetect I notice that the for audio only FCPXML, the column for the **Audio Role & Subrole** is empty.

<img width="1189" alt="Screenshot 2023-01-02 at 10 49 26 AM" src="https://user-images.githubusercontent.com/118706051/210192030-db40a7c5-3593-481b-ad79-21d0b0ddd729.png">

<img width="1393" alt="Screenshot 2023-01-02 at 10 52 02 AM" src="https://user-images.githubusercontent.com/118706051/210192078-5422ce8b-086c-49a7-8c79-2f46d04bcdd3.png">

It should be `Dialogue`, `Effects` or `Music` accordingly. 

Like wise - 
<img width="1309" alt="Screenshot 2023-01-02 at 10 58 12 AM" src="https://user-images.githubusercontent.com/118706051/210192274-e13afb9a-d278-4a19-9b00-db19ad825599.png">

`Video` is one of the default Roles.

**Comment by orchetect** [comment] 2023-01-02 03:18
Is this a regression from 0.1.1?

**Comment by IAmVigneswaran** [comment] 2023-01-02 03:22
> Is this a regression from 0.1.1?

In 0.1.1, since there was a single column for Audio and Video roles, the values would be mixed up. For video clip, it would be listed as Dialogue.

**Comment by orchetect** [comment] 2023-01-02 03:32
Isn't Audio Role & Subrole probably supposed to be empty here? I don't know what's in your FCP project.

In the CSV, the Audio role is being populated by whatever was in the Video role. So when the Video role is not exported to XML, there is no video role at all, and thus no audio role. Just in this particular circumstance.

<img width="1309" alt="Screenshot 2023-01-02 at 10 58 12 AM" src="https://user-images.githubusercontent.com/118706051/210192274-e13afb9a-d278-4a19-9b00-db19ad825599.png">

In an empty FCP project, if I add a Basic Title, it only takes on the "Titles" video role. It does not have an audio role at all. Looking at the raw XML, there are no roles at all within it.

What are you proposing? It's not easy in this case to determine roles for XML contents that have no roles. A role is only written to the XML if it's non-default. So this would imply that we are guessing what default roles are based on other information such as the effect name. It's possible but very dodgy.

**Comment by orchetect** [comment] 2023-01-02 03:58
Just working on something now. I think I know what we need to do here.

**Comment by IAmVigneswaran** [comment] 2023-01-02 03:59
> Isn't Audio Role & Subrole probably supposed to be empty here?

I might have overlooked this. It should not be empty from what I had in mind.

> What are you proposing?

The default role for video should be `Video`. And the default role for Audio should be `Dialogue`.

If any audio clip are tagged with `Music` or `Effects`, they should be reflected accordingly.

For example - 

![](https://user-images.githubusercontent.com/118706051/210192078-5422ce8b-086c-49a7-8c79-2f46d04bcdd3.png)

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fcpxml>

Its XML

```
<fcpxml version="1.10">
    <resources>
        <format id="r1" name="FFVideoFormat1080p2398" frameDuration="1001/24000s" width="1920" height="1080" colorSpace="1-1-1 (Rec. 709)"/>
        <asset id="r2" name="Interstellar Soundtrack - No Time for Caution" uid="7B6E7477652CFB3F66E2520EA95F18E2" start="0s" duration="10860590/44100s" hasAudio="1" audioSources="1" audioChannels="2" audioRate="44100">
            <media-rep kind="original-media" sig="7B6E7477652CFB3F66E2520EA95F18E2" src="file:///Users/xxx/Desktop/Marker_Data/FCP/Media/Interstellar%20Soundtrack%20-%20No%20Time%20for%20Caution.wav">
                <bookmark>Ym9va1QDAAAAAAQQMAAAAJvFToRaKIZYb0CqjH3MkEm5S4fT6B1Sh5bEYFL6QrsTUAIAAAQAAAADAwAAABgAKAUAAAABAQAAVXNlcnMAAAACAAAAAQEAAHZyAAAHAAAAAQEAAERlc2t0b3AACwAAAAEBAABNYXJrZXJfRGF0YQADAAAAAQEAAEZDUAAFAAAAAQEAAE1lZGlhAAAAMQAAAAEBAABJbnRlcnN0ZWxsYXIgU291bmR0cmFjayAtIE5vIFRpbWUgZm9yIENhdXRpb24ud2F2AAAAHAAAAAEGAAAQAAAAIAAAACwAAAA8AAAAUAAAAFwAAABsAAAACAAAAAQDAADcZQAAAAAAAAgAAAAEAwAAa4kAAAAAAAAIAAAABAMAAHCJAAAAAAAACAAAAAQDAACXOgQBAAAAAAgAAAAEAwAA2p8QAQAAAAAIAAAABAMAAKigEAEAAAAACAAAAAQDAACroBABAAAAABwAAAABBgAAzAAAANwAAADsAAAA/AAAAAwBAAAcAQAALAEAAAgAAAAABAAAQcRS7PN3Ok4YAAAAAQIAAAEAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAgAAAAEAwAABQAAAAAAAAAEAAAAAwMAAPUBAAAIAAAAAQkAAGZpbGU6Ly8vDAAAAAEBAABNYWNpbnRvc2ggSEQIAAAABAMAAACwYG50AAAACAAAAAAEAABBxHvxOwAAACQAAAABAQAAOTc2MjU2MUEtOTRDNy00NThGLTgwMTEtNTJBQ0ZCMEVGMDI2GAAAAAECAACBAAAAAQAAAO8TAAABAAAAAAAAAAAAAAABAAAAAQEAAC8AAAAAAAAAAQUAAMwAAAD+////AQAAAAAAAAAQAAAABBAAAKgAAAAAAAAABRAAADwBAAAAAAAAEBAAAHABAAAAAAAAQBAAAGABAAAAAAAAAiAAADwCAAAAAAAABSAAAKwBAAAAAAAAECAAALwBAAAAAAAAESAAAPABAAAAAAAAEiAAANABAAAAAAAAEyAAAOABAAAAAAAAICAAABwCAAAAAAAAMCAAAEgCAAAAAAAAAcAAAJABAAAAAAAAEcAAACAAAAAAAAAAEsAAAKABAAAAAAAAENAAAAQAAAAAAAAA</bookmark>
            </media-rep>
            <metadata>
                <md key="com.apple.proapps.mio.ingestDate" value="2022-08-12 08:46:10 +0800"/>
            </metadata>
        </asset>
        <asset id="r3" name="Water Lake 3" uid="3E24A33F767D8CCD3CDF7CA54E0FF6E7" start="0s" duration="2993454/48000s" hasAudio="1" audioSources="1" audioChannels="2" audioRate="48000">
            <media-rep kind="original-media" sig="3E24A33F767D8CCD3CDF7CA54E0FF6E7" src="file:///Users/xxx/Desktop/Markers_CLI_Tool/FCP/Markers.fcpbundle/Demo%201/Original%20Media/Water%20Lake%203.caf">
                <bookmark>Ym9va5gDAAAAAAQQMAAAAEpGSYEEHtmd2wcpqKXW5pEJQAPww3dAL5eInUNubcjJlAIAAAQAAAADAwAAABgAKAUAAAABAQAAVXNlcnMAAAACAAAAAQEAAHZyAAAHAAAAAQEAAERlc2t0b3AAEAAAAAEBAABNYXJrZXJzX0NMSV9Ub29sAwAAAAEBAABGQ1AAEQAAAAEBAABNYXJrZXJzLmZjcGJ1bmRsZQAAAAYAAAABAQAARGVtbyAxAAAOAAAAAQEAAE9yaWdpbmFsIE1lZGlhAAAQAAAAAQEAAFdhdGVyIExha2UgMy5jYWYkAAAAAQYAABAAAAAgAAAALAAAADwAAABUAAAAYAAAAHwAAACMAAAApAAAAAgAAAAEAwAA3GUAAAAAAAAIAAAABAMAAGuJAAAAAAAACAAAAAQDAABwiQAAAAAAAAgAAAAEAwAAa19YAQAAAAAIAAAABAMAAJhfWAEAAAAACAAAAAQDAACtX1gBAAAAAAgAAAAEAwAAsF9YAQAAAAAIAAAABAMAANthWAEAAAAACAAAAAQDAADcYVgBAAAAACQAAAABBgAA6AAAAPgAAAAIAQAAGAEAACgBAAA4AQAASAEAAFgBAABoAQAACAAAAAAEAABBs6i2wwAAABgAAAABAgAAAQAAAAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAAHAAAAAAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8MAAAAAQEAAE1hY2ludG9zaCBIRAgAAAAEAwAAALBgbnQAAAAIAAAAAAQAAEHEe/E7AAAAJAAAAAEBAAA5NzYyNTYxQS05NEM3LTQ1OEYtODAxMS01MkFDRkIwRUYwMjYYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAAzAAAAP7///8BAAAAAAAAABAAAAAEEAAAvAAAAAAAAAAFEAAAeAEAAAAAAAAQEAAAtAEAAAAAAABAEAAApAEAAAAAAAACIAAAgAIAAAAAAAAFIAAA8AEAAAAAAAAQIAAAAAIAAAAAAAARIAAANAIAAAAAAAASIAAAFAIAAAAAAAATIAAAJAIAAAAAAAAgIAAAYAIAAAAAAAAwIAAAjAIAAAAAAAABwAAA1AEAAAAAAAARwAAAIAAAAAAAAAASwAAA5AEAAAAAAAAQ0AAABAAAAAAAAAA=</bookmark>
            </media-rep>
            <metadata>
                <md key="com.apple.proapps.mio.ingestDate" value="2022-09-06 20:24:47 +0800"/>
            </metadata>
        </asset>
        <format id="r4" name="FFVideoFormatRateUndefined"/>
    </resources>
    <library location="file:///Users/xxx/Desktop/Markers_CLI_Tool/FCP/Markers.fcpbundle/">
        <event name="Demo 1" uid="EC5161E6-24C8-482D-9842-228902DFA148">
            <project name="Audio Only_01" uid="7BC72EC1-4526-4375-A70B-B4CA8293C6EC" modDate="2022-09-06 20:25:39 +0800">
                <sequence format="r1" duration="44901810/720000s" tcStart="0s" tcFormat="NDF" audioLayout="stereo" audioRate="48k">
                    <spine>
                        <asset-clip ref="r2" offset="0s" name="Interstellar Soundtrack - No Time for Caution" duration="1209208/24000s" audioRole="dialogue">
                            <asset-clip ref="r3" lane="-1" offset="0s" name="Water Lake 3" duration="44901810/720000s" format="r4" audioRole="effects">
                                <marker start="5017843/120000s" duration="1/48000s" value="Marker 3"/>
                                <marker start="3433261/60000s" duration="1/48000s" value="Marker 4"/>
                            </asset-clip>
                            <marker start="6162263/720000s" duration="1/48000s" value="Marker 1"/>
                            <marker start="5061859/180000s" duration="1/48000s" value="Marker 2"/>
                            <audio-channel-source srcCh="1, 2" role="music.music-1"/>
                        </asset-clip>
                        <gap name="Gap" offset="1209208/24000s" start="86400314/24000s" duration="287287/24000s"/>
                    </spine>
                </sequence>
            </project>
        </event>
        <smart-collection name="Projects" match="all">
            <match-clip rule="is" type="project"/>
        </smart-collection>
        <smart-collection name="All Video" match="any">
            <match-media rule="is" type="videoOnly"/>
            <match-media rule="is" type="videoWithAudio"/>
        </smart-collection>
        <smart-collection name="Audio Only" match="all">
            <match-media rule="is" type="audioOnly"/>
        </smart-collection>
        <smart-collection name="Stills" match="all">
            <match-media rule="is" type="stills"/>
        </smart-collection>
        <smart-collection name="Favorites" match="all">
            <match-ratings value="favorites"/>
        </smart-collection>
    </library>
</fcpxml>

```

You can see it is tagged as `effects`. Which should be stated as `Effects` in the csv.
`<asset-clip ref="r3" lane="-1" offset="0s" name="Water Lake 3" duration="44901810/720000s" format="r4" audioRole="effects">`

And

tagged as `music.music-1`. Which should be stated as `Music` in the csv.
`<audio-channel-source srcCh="1, 2" role="music.music-1"/>`

**Comment by orchetect** [comment] 2023-01-02 04:05
> The default role for video should be Video. And the default role for Audio should be Dialogue.

What I'm saying is it's more complex than that. Default roles differ depending on clip type. For example, titles have a default role of "Titles". But raw video footage has a default role of "Video". These may not be the only unique conditions until we stumble upon more through trial & error in testing various clip types.

> You can see it is tagged as `effects`. Which should be stated as `Effects` in the csv. `<asset-clip ref="r3" lane="-1" offset="0s" name="Water Lake 3" duration="44901810/720000s" format="r4" audioRole="effects">`

This is already current MarkersExtractor behavior.

> tagged as `music.music-1`. Which should be stated as `Music` in the csv. `<audio-channel-source srcCh="1, 2" role="music.music-1"/>`

Currently we're outputting whatever is literally in the XML. This would output to CSV as "Music.Music-1". To interpret that as "Music" is more involved and would require a heuristic to parse out. Possible, just going to take more work and testing.

**Comment by orchetect** [comment] 2023-01-02 04:17
What is our desired behavior when a clip only has a video role? Such as Basic Titles (as mentioned earlier in this thread)?

FCP uses a default video role of "Titles" but there is no audio role assignable even if you try.

<img width="464" alt="titles-audio-role" src="https://user-images.githubusercontent.com/11605557/210194758-b63fd4f2-ed93-4767-9f66-c1426daa79e7.png">

In this case, FCP does not allow nor assign a default audio role.

Ergo, our CSV should have a "Titles" video role but an empty Audio Role in this case.

**Comment by orchetect** [comment] 2023-01-02 04:21
FYI, we already have a special case to handle titles that inserts Titles as a video role.

https://github.com/TheAcharya/MarkersExtractor/blob/740676cab050693814c5b201520c0d1bb12e61d9/Sources/MarkersExtractor/Extractors/FCPXMLMarkerExtractor.swift#L275-L277

Which is what you can see in your screenshot:

<img width="1309" alt="Screenshot 2023-01-02 at 10 58 12 AM" src="https://user-images.githubusercontent.com/118706051/210192274-e13afb9a-d278-4a19-9b00-db19ad825599.png">

So we would expand on that concept for other clip types.

**Comment by orchetect** [comment] 2023-01-02 05:08
> > tagged as `music.music-1`. Which should be stated as `Music` in the csv. `<audio-channel-source srcCh="1, 2" role="music.music-1"/>`
> 
> Currently we're outputting whatever is literally in the XML. This would output to CSV as "Music.Music-1". To interpret that as "Music" is more involved and would require a heuristic to parse out. Possible, just going to take more work and testing.

This is now implemented. Will be in next alpha build.

**Comment by orchetect** [comment] 2023-01-02 05:20
So with updates I just made, it basically reflects an accurate/reasonable representation of what appears in FCP.

The video clips use default "Video" video role and "Dialogue" audio role. This is what FCP reflects.

Titles uses video role "Titles" and empty audio role. This is what FCP reflects.

The markers with clip name "Clouds" are in fact a titles clip but has a custom video role called "Sample Rate". Again, it uses an empty audio role because FCP does not allow a default nor does it assign one.

<img width="857" alt="roles" src="https://user-images.githubusercontent.com/11605557/210197081-2f1cc224-5b30-4d60-b0f0-050239fddac9.png">

**Comment by orchetect** [comment] 2023-01-02 05:21
If Notion requires non-empty cells for the roles fields in the CSV, we could perhaps put in a placeholder string such as "n/a" or "-" or "<Not Assigned>".

That would seem more logical than using an assumed default that FCP does not actually use.

**Comment by orchetect** [comment] 2023-01-02 05:29
New alpha if you want to test:

https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.2.0-alpha-20230101.1

**Comment by IAmVigneswaran** [comment] 2023-01-02 06:24
> New alpha if you want to test:
> 
> https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.2.0-alpha-20230101.1

Thanks for the new build!

> If Notion requires non-empty cells for the roles fields in the CSV, we could perhaps put in a placeholder string such as "n/a" or "-" or "<Not Assigned>".
> 
> That would seem more logical than using an assumed default that FCP does not actually use.
> 

Yes, `Not Assigned`would work.

We are on the right track. Further refinement is required. Example - Water Lake 3.caf has audio role of Effects, and it is tagged with `Video`.

<img width="1039" alt="Screenshot 2023-01-02 at 2 08 43 PM" src="https://user-images.githubusercontent.com/118706051/210199423-628c6627-38fa-4dfa-8838-d051cfb82332.png">

![](https://user-images.githubusercontent.com/118706051/210192078-5422ce8b-086c-49a7-8c79-2f46d04bcdd3.png)

Hence in the new case, it would be `Not Assigned`. 

Here are still empty values for some cases.

<img width="671" alt="Screenshot 2023-01-02 at 2 16 27 PM" src="https://user-images.githubusercontent.com/118706051/210199881-9100fb71-595a-42c1-b11a-83a1b0172482.png">

For example - Nature Makes You Happy.mp4 should also have a `Video` tag for the

**Comment by orchetect** [comment] 2023-01-03 07:22
> Yes, `Not Assigned` would work.

Implemented. Will be in next alpha.

Will address the remaining specific role conditions as time allows.

**Comment by IAmVigneswaran** [comment] 2023-01-03 07:33
Thank you!

**Comment by orchetect** [comment] 2023-04-28 05:32
@IAmVigneswaran Is this still an outstanding issue? Are there specific default roles that still need implementing?

**Comment by IAmVigneswaran** [comment] 2023-04-28 07:12
> @IAmVigneswaran Is this still an outstanding issue? Are there specific default roles that still need implementing?

I don't think there is any outstanding problem for this issue. All the default roles have been implemented. Thank you.

**Closed** 2023-04-28 07:19 UTC
Labels: bug, export metadata set
